services:
  # APPLICATION
  application:
    container_name: fastybird-application
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    depends_on:
      - database
    environment:
      # Container specific environment variables
      TZ: ${APP_TZ:-UTC}
      PHP_DATE_TIMEZONE: ${APP_TZ:-UTC}
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      # Application specific environment variables
      APP_ENV: "dev"
      FB_CONFIG_DIR: /app/var/config
      FB_APP_PARAMETER__DATABASE_HOST: database
      FB_APP_PARAMETER__DATABASE_PORT: 3306
      FB_APP_PARAMETER__DATABASE_USERNAME: ${DATABASE_USERNAME:-fastybird}
      FB_APP_PARAMETER__DATABASE_PASSWORD: ${DATABASE_PASSWORD:-fastybird}
      FB_APP_PARAMETER__DATABASE_DBNAME: ${DATABASE_DBNAME:-fastybird_dev}
      FB_APP_PARAMETER__REDIS_HOST: redis
      FB_APP_PARAMETER__REDIS_PORT: 6379
      FB_APP_PARAMETER__SECURITY_SIGNATURE: ${SECURITY_SIGNATURE}
      FB_APP_PARAMETER__API_PREFIXED_MODULES: ${API_PREFIXED_MODULES:-true}
    volumes:
      - ./:/app:delegated
      - ./.docker/dev/php.ini:/etc/php/8.1/fpm/php.ini:delegated
      - ./.docker/dev/php.ini:/etc/php/8.1/cli/php.ini:delegated
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${WORKER_STATUS_PORT:-9001}:9001"
      - "6666:6666/udp"
      - "6667:6667/udp"
      - "6668:6668/udp"
      - "5683:5683/udp"
      - "51827:51827/udp"
    networks:
      - fastybird
    devices:
      - "/dev/tty.usbserial-21420:/dev/ttyUSB0"

  # MYSQL DATABASE STORAGE
  database:
    container_name: fastybird-database
    image: mariadb
    platform: linux/amd64
    environment:
      # Container specific environment variables
      TZ: ${APP_TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-root}
      MYSQL_USER: ${DATABASE_USERNAME:-fastybird}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-fastybird}
      MYSQL_DATABASE: ${DATABASE_DBNAME:-fastybird_dev}
    volumes:
      - mysql-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - fastybird

  # REDIS STORAGE
  redis:
    container_name: fastybird-redis
    image: redis
    volumes:
      - redis-other:/var/lib/redis:rw
      - redis-data:/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/redis/other:/var/lib/redis:rw,delegated
      # - ./docker/redis/data:/data:rw,delegated
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - fastybird

  redis-commander:
    container_name: fastybird-redis-client
    image: rediscommander/redis-commander
    restart: always
    environment:
      # Container specific environment variables
      REDIS_HOSTS: local:redis:6379
    ports:
      - "${REDIS_ADMIN_PORT:-8081}:8081"
    networks:
      - fastybird

  # MQTT
  mqtt:
    container_name: fastybird-mqtt
    image: eclipse-mosquitto
    volumes:
      - mqtt-data:/mosquitto/data:rw
      - mqtt-log:/mosquitto/log:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mqtt/data:/mosquitto/data:rw,delegated
    ports:
      - "${MQTT_PORT:-1883}:1883"
    networks:
      - fastybird

networks:
  fastybird:
    driver: bridge

volumes:
  mysql-data:
  redis-other:
  redis-data:
  mqtt-data:
  mqtt-log:
