services:
  # APPLICATION
  application:
    container_name: fastybird-application
    build:
      context: .
      dockerfile: .docker/dev/Dockerfile
    depends_on:
      - database
    environment:
      # Container specific environment variables
      TZ: ${APP_TZ:-UTC}
      PHP_DATE_TIMEZONE: ${APP_TZ:-UTC}
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      # Application specific environment variables
      APP_ENV: "dev"
      FB_CONFIG_DIR: /app/var/config
      FB_APP_PARAMETER__DATABASE_HOST: 127.0.0.1
      FB_APP_PARAMETER__DATABASE_PORT: 3306
      FB_APP_PARAMETER__DATABASE_USERNAME: ${DATABASE_USERNAME:-fastybird}
      FB_APP_PARAMETER__DATABASE_PASSWORD: ${DATABASE_PASSWORD:-fastybird}
      FB_APP_PARAMETER__DATABASE_DBNAME: ${DATABASE_DBNAME:-fastybird_dev}
      FB_APP_PARAMETER__REDIS_HOST: 127.0.0.1
      FB_APP_PARAMETER__REDIS_PORT: 6379
      FB_APP_PARAMETER__SECURITY_SIGNATURE: ${SECURITY_SIGNATURE}
      FB_APP_PARAMETER__API_PREFIXED_MODULES: ${API_PREFIXED_MODULES:-true}
    volumes:
      - ./:/app:delegated
      - ./.docker/dev/php.ini:/etc/php/8.1/fpm/php.ini:delegated
      - ./.docker/dev/php.ini:/etc/php/8.1/cli/php.ini:delegated
    ports:
      - "${HTTP_PORT:-8000}:8000"
      - "${WS_PORT:-8888}:8888"
      - "${WORKER_STATUS_PORT:-9001}:9001"
      - "43323:43323"
    network_mode: host
    #devices:
    #  - "/dev/tty.usbserial-31420:/dev/ttyUSB0"

  # MYSQL DATABASE STORAGE
  database:
    container_name: fastybird-database
    image: mariadb
    environment:
      # Container specific environment variables
      TZ: ${APP_TZ:-UTC}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-root}
      MYSQL_USER: ${DATABASE_USERNAME:-fastybird}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD:-fastybird}
      MYSQL_DATABASE: ${DATABASE_DBNAME:-fastybird_dev}
    volumes:
      - mysql-dev-data:/var/lib/mysql:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mysql/data:/var/lib/mysql:rw,delegated
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - fastybird

  # REDIS STORAGE
  redis:
    container_name: fastybird-redis
    image: redis
    volumes:
      - redis-dev-other:/var/lib/redis:rw
      - redis-dev-data:/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/redis/other:/var/lib/redis:rw,delegated
      # - ./docker/redis/data:/data:rw,delegated
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks:
      - fastybird

  redis-commander:
    container_name: fastybird-redis-client
    image: rediscommander/redis-commander
    restart: always
    environment:
      # Container specific environment variables
      REDIS_HOSTS: local:redis:6379
    ports:
      - "${REDIS_ADMIN_PORT:-8081}:8081"
    networks:
      - fastybird

  # COUCH DB STORAGE
  couchdb:
    container_name: fastybird-couchdb
    image: couchdb
    environment:
      # Container specific environment variables
      COUCHDB_USER: ${COUCHDB_USERNAME:-admin}
      COUCHDB_PASSWORD: ${COUCHDB_PASSWORD:-admin}
    volumes:
      - couchdb-dev-data:/opt/couchdb/data:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/couchdb/data:/opt/couchdb/data:rw,delegated
    ports:
      - "${COUCHDB_PORT:-5984}:5984"
    networks:
      - fastybird

  # RABBIT MQ EXCHANGE
  rabbitmq:
    container_name: fastybird-rabbitmq
    image: rabbitmq:management
    environment:
      # Container specific environment variables
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-admin}
    volumes:
      - rabbitmq-dev-data:/var/lib/rabbitmq:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/rabbitmq/data:/var/lib/rabbitmq:rw,delegated
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    networks:
      - fastybird

  # MQTT
  mqtt:
    container_name: fastybird-mqtt
    image: eclipse-mosquitto
    volumes:
      - mqtt-dev-data:/mosquitto/data:rw
      - mqtt-dev-log:/mosquitto/log:rw
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/mqtt/data:/mosquitto/data:rw,delegated
    ports:
      - "${MQTT_PORT:-1883}:1883"
    networks:
      - fastybird

networks:
  fastybird:
    driver: bridge

volumes:
  mysql-dev-data:
  redis-dev-other:
  redis-dev-data:
  couchdb-dev-data:
  mqtt-dev-data:
  mqtt-dev-log:
  rabbitmq-dev-data: