#!/usr/bin/env php
<?php declare(strict_types = 1);

use const DIRECTORY_SEPARATOR as DS;

if (PHP_SAPI != 'cli') {
	exit('Script needs to be run from Command Line Interface (cli)');
}

include(__DIR__ . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . 'fb-console.php');