<?php declare(strict_types = 1);

namespace FastyBird\Bridge\VieraConnectorHomeKitConnector\Tests\Cases\Unit\Builders;

use Error;
use FastyBird\Bridge\VieraConnectorHomeKitConnector\Builders;
use FastyBird\Bridge\VieraConnectorHomeKitConnector\Entities;
use FastyBird\Bridge\VieraConnectorHomeKitConnector\Exceptions;
use FastyBird\Bridge\VieraConnectorHomeKitConnector\Tests;
use FastyBird\Connector\HomeKit\Entities as HomeKitEntities;
use FastyBird\Connector\Viera\Entities as VieraEntities;
use FastyBird\Library\Application\Exceptions as ApplicationExceptions;
use FastyBird\Library\Metadata\Exceptions as MetadataExceptions;
use FastyBird\Module\Devices\Models as DevicesModels;
use FastyBird\Module\Devices\Queries as DevicesQueries;
use IPub\DoctrineCrud\Exceptions as DoctrineCrudExceptions;
use Nette\DI;
use RuntimeException;

/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
final class BuilderTest extends Tests\Cases\Unit\DbTestCase
{

	/**
	 * @param array<mixed> $expectedChannels
	 * @param array<mixed> $expectedChannelsProperties
	 *
	 * @throws ApplicationExceptions\InvalidArgument
	 * @throws ApplicationExceptions\InvalidState
	 * @throws ApplicationExceptions\Runtime
	 * @throws DI\MissingServiceException
	 * @throws DoctrineCrudExceptions\InvalidArgument
	 * @throws Exceptions\InvalidArgument
	 * @throws Exceptions\InvalidState
	 * @throws Error
	 * @throws MetadataExceptions\InvalidArgument
	 * @throws RuntimeException
	 *
	 * @dataProvider builder
	 */
	public function testBuild(
		string $vieraIdentifier,
		int $expectedChannelsCnt,
		array $expectedChannels,
		array $expectedChannelsProperties,
	): void
	{
		$builder = $this->getContainer()->getByType(Builders\Builder::class);

		$connectorsRepository = $this->getContainer()->getByType(
			DevicesModels\Entities\Connectors\ConnectorsRepository::class,
		);

		$devicesRepository = $this->getContainer()->getByType(DevicesModels\Entities\Devices\DevicesRepository::class);

		$findConnectorQuery = new DevicesQueries\Entities\FindConnectors();
		$findConnectorQuery->byIdentifier('homekit');

		$connector = $connectorsRepository->findOneBy($findConnectorQuery);

		self::assertInstanceOf(HomeKitEntities\Connectors\Connector::class, $connector);

		$findVieraQuery = new DevicesQueries\Entities\FindDevices();
		$findVieraQuery->byIdentifier($vieraIdentifier);

		$viera = $devicesRepository->findOneBy($findVieraQuery, VieraEntities\Devices\Device::class);

		self::assertInstanceOf(VieraEntities\Devices\Device::class, $viera);

		$bridge = $builder->build($viera, $connector);

		self::assertSame($viera, $bridge->getParent());

		self::assertCount($expectedChannelsCnt, $bridge->getChannels());
		self::assertInstanceOf(Entities\Channels\Viera::class, $bridge->getChannels()[0]);

		$actual = [];

		foreach ($bridge->getChannels() as $channel) {
			$channelData = $channel->toArray();

			unset($channelData['id']);
			unset($channelData['properties']);
			unset($channelData['controls']);
			unset($channelData['device']);

			$actual[$channel->getIdentifier()] = $channelData;
		}

		self::assertSame($expectedChannels, $actual);

		$actual = [];

		foreach ($bridge->getChannels() as $channel) {
			$actual[$channel->getIdentifier()] = [];

			foreach ($channel->getProperties() as $property) {
				$propertyData = $property->toArray();

				unset($propertyData['id']);
				unset($propertyData['channel']);

				$actual[$channel->getIdentifier()][$property->getIdentifier()] = $propertyData;
			}
		}

		self::assertSame($expectedChannelsProperties, $actual);
	}

	/**
	 * @return array<string, array<string|int|array<mixed>|null>>
	 */
	public static function builder(): array
	{
		return [
			'Viera 1 - edit' => [
				'4D454930-0200-1000-8001-80C755230D19',
				12,
				[
					'television_1' => [
						'type' => 'viera-connector-homekit-connector-bridge-television',
						'category' => 'generic',
						'identifier' => 'television_1',
						'name' => 'Television',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_1' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_1',
						'name' => 'TV',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'television_speaker_1' => [
						'type' => 'viera-connector-homekit-connector-bridge-television-speaker',
						'category' => 'generic',
						'identifier' => 'television_speaker_1',
						'name' => 'Television speaker',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_2' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_2',
						'name' => 'Hdmi1',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_5' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_5',
						'name' => 'Apps market',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_8' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_8',
						'name' => 'Plex',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_3' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_3',
						'name' => 'Hdmi2',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_4' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_4',
						'name' => 'Hdmi3',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_7' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_7',
						'name' => 'Youtube',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_9' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_9',
						'name' => 'Apple tv+',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_10' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_10',
						'name' => 'Youtube music',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
					'input_source_6' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_6',
						'name' => 'Netflix',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2024-08-20T11:00:00+02:00',
						'updated_at' => '2024-08-20T11:00:00+02:00',
					],
				],
				[
					'television_1' => [
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Living Room TV',
							'owner' => null,
							'children' => [],
						],
						'remote_key' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'remote_key',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => 'a819734a-8b27-43b9-8ed3-7e62285e2b5d',
							'settable' => true,
							'queryable' => false,
						],
						'active' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'active',
							'name' => null,
							'data_type' => 'bool',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => 'd6df8598-c2c0-40ec-8a14-b08823e74b9c',
							'settable' => true,
							'queryable' => true,
						],
						'sleep_discovery_mode' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'sleep_discovery_mode',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'active_identifier' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'active_identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_1' => [
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '2',
							'owner' => null,
							'children' => [],
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 500,
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'TV',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'TV',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
					],
					'television_speaker_1' => [
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Living Room TV speaker',
							'owner' => null,
							'children' => [],
						],
						'volume' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'volume',
							'name' => null,
							'data_type' => 'uchar',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => 100.0,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '98ee724b-093f-4289-9207-f555a1ed1d86',
							'settable' => true,
							'queryable' => true,
						],
						'mute' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'mute',
							'name' => null,
							'data_type' => 'bool',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '8e02bb38-08d7-4595-9635-8d1486450ec5',
							'settable' => true,
							'queryable' => true,
						],
						'volume_selector' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'volume_selector',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => 'a819734a-8b27-43b9-8ed3-7e62285e2b5d',
							'settable' => true,
							'queryable' => false,
						],
						'active' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'active',
							'name' => null,
							'data_type' => 'bool',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => 'd6df8598-c2c0-40ec-8a14-b08823e74b9c',
							'settable' => true,
							'queryable' => true,
						],
						'volume_control_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'volume_control_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '3',
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_2' => [
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Hdmi1',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 1,
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Hdmi1',
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '3',
							'owner' => null,
							'children' => [],
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_5' => [
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '10',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 387_878_700_000_102,
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Apps market',
							'owner' => null,
							'children' => [],
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Apps market',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
					],
					'input_source_8' => [
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 76_010_507_000_001,
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Plex',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Plex',
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '10',
							'owner' => null,
							'children' => [],
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
					],
					'input_source_3' => [
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '3',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Hdmi2',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 2,
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Hdmi2',
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_4' => [
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Hdmi3',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Hdmi3',
							'owner' => null,
							'children' => [],
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 3,
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '3',
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_7' => [
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Youtube',
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '10',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Youtube',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 70_000_200_180_001,
							'owner' => null,
							'children' => [],
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_9' => [
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 70_003_000_000_001,
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '10',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Apple tv+',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Apple tv+',
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_10' => [
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Youtube music',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Youtube music',
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '10',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 70_003_100_000_001,
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
					],
					'input_source_6' => [
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Netflix',
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '10',
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 'Netflix',
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'owner' => null,
							'parent' => '65a4b39b-1bbb-41f3-93ca-898e9f088df3',
							'settable' => true,
							'queryable' => false,
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2024-08-20T11:00:00+02:00',
							'updated_at' => '2024-08-20T11:00:00+02:00',
							'value' => 10_000_200_000_001,
							'owner' => null,
							'children' => [],
						],
					],
				],
			],
			'Viera 2 - create' => [
				'4D454930-0200-1000-8001-A81374B30314',
				3,
				[
					'television_1' => [
						'type' => 'viera-connector-homekit-connector-bridge-television',
						'category' => 'generic',
						'identifier' => 'television_1',
						'name' => 'Television',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2020-04-01T12:00:00+00:00',
						'updated_at' => '2020-04-01T12:00:00+00:00',
					],
					'television_speaker_1' => [
						'type' => 'viera-connector-homekit-connector-bridge-television-speaker',
						'category' => 'generic',
						'identifier' => 'television_speaker_1',
						'name' => 'Television speaker',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2020-04-01T12:00:00+00:00',
						'updated_at' => '2020-04-01T12:00:00+00:00',
					],
					'input_source_1' => [
						'type' => 'viera-connector-homekit-connector-bridge-input-source',
						'category' => 'generic',
						'identifier' => 'input_source_1',
						'name' => 'TV',
						'comment' => null,
						'connector' => '451ab010-f500-4eff-8289-9ed09e56a887',
						'owner' => null,
						'created_at' => '2020-04-01T12:00:00+00:00',
						'updated_at' => '2020-04-01T12:00:00+00:00',
					],
				],
				[
					'television_1' => [
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => 'Bedroom TV',
							'owner' => null,
							'children' => [],
						],
						'active' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'active',
							'name' => null,
							'data_type' => 'bool',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => 'f9c913c5-fc40-44a0-8197-7fb446557c4a',
							'settable' => true,
							'queryable' => true,
						],
						'sleep_discovery_mode' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'sleep_discovery_mode',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'remote_key' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'remote_key',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => '1759c576-91b5-4254-b711-140c0a161cb0',
							'settable' => true,
							'queryable' => false,
						],
						'active_identifier' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'active_identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
					],
					'television_speaker_1' => [
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => 'Bedroom TV speaker',
							'owner' => null,
							'children' => [],
						],
						'active' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'active',
							'name' => null,
							'data_type' => 'bool',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => 'f9c913c5-fc40-44a0-8197-7fb446557c4a',
							'settable' => true,
							'queryable' => true,
						],
						'volume' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'volume',
							'name' => null,
							'data_type' => 'uchar',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => 100.0,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => '2911f329-66d5-4a4d-8b98-e6f65e3d104b',
							'settable' => true,
							'queryable' => true,
						],
						'volume_control_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'volume_control_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => '3',
							'owner' => null,
							'children' => [],
						],
						'volume_selector' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'volume_selector',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => '1759c576-91b5-4254-b711-140c0a161cb0',
							'settable' => true,
							'queryable' => false,
						],
						'mute' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'mute',
							'name' => null,
							'data_type' => 'bool',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => '8c1ef3c8-eeb2-4627-a141-a585804439ff',
							'settable' => true,
							'queryable' => true,
						],
					],
					'input_source_1' => [
						'configured_name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'configured_name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => 'TV',
							'owner' => null,
							'children' => [],
						],
						'name' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'name',
							'name' => null,
							'data_type' => 'string',
							'unit' => null,
							'format' => null,
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => 'TV',
							'owner' => null,
							'children' => [],
						],
						'input_source_type' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'input_source_type',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
								4 => '4',
								5 => '5',
								6 => '6',
								7 => '7',
								8 => '8',
								9 => '9',
								10 => '10',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => '2',
							'owner' => null,
							'children' => [],
						],
						'is_configured' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'is_configured',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '1',
								1 => '0',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => '1',
							'owner' => null,
							'children' => [],
						],
						'identifier' => [
							'type' => 'variable',
							'category' => 'generic',
							'identifier' => 'identifier',
							'name' => null,
							'data_type' => 'uint',
							'unit' => null,
							'format' => [
								0 => 0.0,
								1 => null,
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => 0,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'value' => 500,
							'owner' => null,
							'children' => [],
						],
						'current_visibility_state' => [
							'type' => 'mapped',
							'category' => 'generic',
							'identifier' => 'current_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
								2 => '2',
								3 => '3',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => null,
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'owner' => null,
							'parent' => '35184656-89a8-486c-9fd4-390d6f1482e8',
							'settable' => true,
							'queryable' => false,
						],
						'target_visibility_state' => [
							'type' => 'dynamic',
							'category' => 'generic',
							'identifier' => 'target_visibility_state',
							'name' => null,
							'data_type' => 'enum',
							'unit' => null,
							'format' => [
								0 => '0',
								1 => '1',
							],
							'invalid' => null,
							'scale' => null,
							'step' => null,
							'default' => '0',
							'value_transformer' => null,
							'created_at' => '2020-04-01T12:00:00+00:00',
							'updated_at' => '2020-04-01T12:00:00+00:00',
							'settable' => true,
							'queryable' => false,
							'owner' => null,
							'children' => [],
						],
					],
				],
			],
		];
	}

}
