name: "build"

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - "main"
    tags:
      - v*
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

env:
  extensions: "json, intl, :php-psr"
  cache-version: "1"
  composer-version: "v2"
  composer-options: "--no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable"
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ORGANIZATION_ACCESS_TOKEN }}"}}'

jobs:
  ci:
    name: "CI"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]

    uses: "FastyBird/.github/workflows/ci-php.yaml@main"
    secrets: "inherit"
    with:
      php-version: "8.2"
      working-directory: ".src/FastyBird/Library/Application"
