name: "build"

on:
  pull_request:
    paths-ignore:
      - "docs/**"
  push:
    branches:
      - "main"
    tags:
      - v*
  schedule:
    - cron: "0 8 * * 1" # At 08:00 on Monday

env:
  extensions: "json, intl, :php-psr"
  cache-version: "1"
  composer-version: "v2"
  composer-options: "--no-interaction --no-progress --prefer-dist --prefer-stable"
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.ORGANIZATION_ACCESS_TOKEN }}"}}'

jobs:
  build_matrix:
    name: "Create list of packages for split"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]

    # This step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.set-matrix.outputs.content }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"

      - name: "Read matrix configuration"
        id: "set-matrix"
        uses: "juliangruber/read-file-action@v1"
        with:
          path: "./.github/workflows/monorepo-matrix.json"

  ci:
    name: "Package CI"
    needs: [ "build_matrix" ]

    uses: "FastyBird/.github/.github/workflows/ci-php.yaml@main"
    secrets: "inherit"
    with:
      php-version: "8.2"
      working-directory: "./src/FastyBird/Library/Application"

    strategy:
      fail-fast: false
      matrix:
        operating-system: [ "ubuntu-latest" ]
