name: "monorepo"

on:
  push:
    branches:
      - "main"
    tags:
      - v*

env:
  extensions: "json"
  cache-version: "1"
  composer-version: "v2"
  composer-install: "composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable"

jobs:
  build_matrix:
    name: "Create list of packages for split"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1" ]
        operating-system: [ "ubuntu-latest" ]

    # This step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Read packages list"
        id: "set-matrix"
        uses: "JoshuaTheMiller/conditional-build-matrix@main"
        with:
          inputFile: "resources/packages.json"
          filter: "[?runOnBranch=='${{ github.ref }}' || runOnBranch=='always']"
          addInclude: "false"

  split_monorepo:
    name: "Create list of packages for split"
    runs-on: "${{ matrix.operating-system }}"
    needs: [ "build_matrix" ]

    strategy:
      fail-fast: false
      matrix:
        runOnBranch: always
        php-version:
          - '8.1'
        operating-system:
          - ubuntu-latest
        package:
          - fb-mqtt-connector
          - homekit-connector
          - modbus-connector
          - shelly-connector
          - tuya-connector
          - exchange
          - metadata
          - devices-module
          - redisdb-plugin
          - web-server-plugin
          - ws-exchange-plugin

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Monorepo Split of ${{ matrix.package }}"
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/github-action-monorepo-split@2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          package-directory: "${{ matrix.package-directory }}"
          split-repository-organization: "fastybird"
          split-repository-name: "${{ matrix.package }}"
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"

      - name: "Monorepo Tagged Split of ${{ matrix.package }}"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/github-action-monorepo-split@2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: "${{ matrix.package-directory }}"
          split-repository-organization: "fastybird"
          split-repository-name: "${{ matrix.package }}"
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
