name: "Split monorepo"

on:
  push:
    branches:
      - "main"
    tags:
      - v*

env:
  extensions: "json"
  cache-version: "1"
  composer-version: "v2"
  composer-install: "composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable"

jobs:
  # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
  # see https://stackoverflow.com/a/62953566/1348344
  provide_packages:
    name: "Create list of packages for split"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1" ]
        operating-system: [ "ubuntu-latest" ]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Get package json list"
        id: "packages"
        run: |
          JSON=$(cat ./resources/packages.json)
          echo "::set-output name=matrix::${JSON//'%'/'%25'}"

    # this step is needed, so the output gets to the next defined job
    outputs:
      matrix: ${{ steps.packages.outputs.matrix }}

  split_monorepo:
    name: "Create list of packages for split"
    runs-on: "${{ matrix.operating-system }}"
    needs: [ "provide_packages" ]

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1" ]
        operating-system: [ "ubuntu-latest" ]
        package: ${{fromJson(needs.provide_packages.outputs.matrix)}}

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Monorepo Split of ${{ matrix.package }}"
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/github-action-monorepo-split@2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          package-directory: 'src/FastyBird/${{ matrix.package }}'
          split-repository-organization: 'fastybird'
          split-repository-name: '${{ matrix.package }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"

      - name: "Monorepo Tagged Split of ${{ matrix.package }}"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/github-action-monorepo-split@2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: 'packages/${{ matrix.package }}'
          split-repository-organization: 'fastybird'
          split-repository-name: '${{ matrix.package }}'
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
