name: "monorepo"

on:
  push:
    branches:
      - "main"
    tags:
      - v*

env:
  extensions: "json"
  cache-version: "1"
  composer-version: "v2"
  composer-install: "composer update --no-interaction --no-progress --no-suggest --prefer-dist --prefer-stable"

jobs:
  split_monorepo:
    name: "Create list of packages for split"
    runs-on: "${{ matrix.operating-system }}"

    strategy:
      fail-fast: false
      matrix:
        php-version: [ "8.1" ]
        operating-system: [ "ubuntu-latest" ]
        include:
          - "fb-mqtt-connector": "src/FastyBird/Connector/FbMqtt"
          - "homekit-connector": "src/FastyBird/Connector/HomeKit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Monorepo Split of ${{ matrix.package }}"
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/github-action-monorepo-split@2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          package-directory: "${{ matrix.package-directory }}"
          split-repository-organization: "fastybird"
          split-repository-name: "${{ matrix.package }}"
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"

      - name: "Monorepo Tagged Split of ${{ matrix.package }}"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/github-action-monorepo-split@2.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package-directory: "${{ matrix.package-directory }}"
          split-repository-organization: "fastybird"
          split-repository-name: "${{ matrix.package }}"
          user-name: "GitHub Action"
          user-email: "action@github.com"
          branch: "main"
